load_module /usr/lib/nginx/modules/ngx_rtmp_module.so;

worker_processes 1;
user www-data;

# docker logs に RTMP イベントを出力する
error_log /dev/stderr info;

events {
    worker_connections 1024;
}

rtmp {
    # 接続ログを stdout (docker logs) に出力
    access_log /dev/stdout;

    server {
        listen 1935;

        chunk_size 4096;
        max_message 1M;

        application live {
            live on;
            record off;

            allow publish all;
            allow play all;

            exec_push /usr/local/bin/publish.sh $name;
            exec_kill_signal term;
        }
    }
}
