worker_processes auto;
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        max_message 1M;

        application live {
            live on;
            record off;

            allow publish all;
            allow play all;

            # ストリーム開始時に publish.sh を起動 → FFmpeg (NVENC) で LL-HLS 生成
            exec_push /usr/local/bin/publish.sh $name;
            exec_kill_signal term;
        }
    }
}
